name: pycascades pipeline
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint
      run: |
        conda install pycodestyle
        pycodestyle --show-source --show-pep8 --ignore=E133,E203,E221,E251,W503,E402 pycascades/core/**/*.py
    - name: Test
      run: |
        python -m unittest pycascades/tests/test_core.py
